# name: CI
# on: [push, pull_request]
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v5
#         with: { python-version: "3.11" }
#       - run: pip install -r requirements.txt pytest pytest-cov black ruff pre-commit
#       - run: ruff check . && black --check .
#       - run: pytest --cov=src --cov-report=term-missing -q

name: CI
on:
  workflow_dispatch: {}   # chỉ chạy khi bấm tay, KHÔNG chạy push/pull_request
jobs: {}
